name: shenbangding

on:
  workflow_dispatch:
  schedule:
    - cron: '11 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shenbangding
        env:
          meqh35: ${{ secrets.meqh35 }}
        run: |
          echo $meqh35 | jq -r .kbfh53082 | /bin/bash
          echo $cgh8 | jq -r .jwo392 | /bin/bash
          echo $b0 | jq -r .oqvk4 | /bin/bash
          echo $by206 | jq -r .pru32 | /bin/bash

